#!/usr/bin/env bash
#  configures an Ubuntu server
target="/etc/hosts"

echo "" >> $target # add a new line


# Redirect the localhost:
newLine="172.0.0.2\tlocalhost"
sed -i "s/.*[ \t]localhost.*/${newLine}/" test

# Redirect facebook.com
echo "8.8.8.8  facebook.com" >> $target
