#!/usr/bin/env bash
#  configures an Ubuntu server
target="/etc/hosts"

# Redirect the localhost:
newLine="127.0.0.2  \tlocalhost"
sed -i "s/.*[ \t]localhost.*/${newLine}/" $target

# Redirect facebook.com
echo "" >> $target # add a new line
echo "8.8.8.8  facebook.com" >> $target
